import {CreateD12BackupReceiptSchema,D12BackupReceiptSchema,type CreateD12BackupReceipt,type D12BackupReceipt} from '@masterflow/shared';
import {getDb,type D12BackupReceiptRow} from '../db/schema.ts';
import {audit} from '../lib/audit.ts';
import {uuid} from '../lib/uuid.ts';
import type {AuthUser} from '../middleware/auth.ts';
function refs(value:string):string[]{const parsed=JSON.parse(value)as unknown;return Array.isArray(parsed)?parsed.filter((item):item is string=>typeof item==='string'):[];}
function toReceipt(row:D12BackupReceiptRow):D12BackupReceipt{return D12BackupReceiptSchema.parse({receipt_id:row.id,owner_id:row.owner_id,target_label:row.target_label,environment_label:row.environment_label,checksum_sha256:row.checksum_sha256,backup_observed_at:row.backup_observed_at,evidence_refs:refs(row.evidence_refs_json),note:row.note,proof_state:row.proof_state,restore_status:row.restore_status,created_at:row.created_at});}
/** Enregistre un backup déclaré ; ne lit, ne copie et ne restaure aucun fichier. */
export function createD12BackupReceipt(actor:AuthUser,input:CreateD12BackupReceipt):D12BackupReceipt{const request=CreateD12BackupReceiptSchema.parse(input),id=uuid(),now=Date.now(),proofState=request.evidence_refs.length?'evidence_attached':'unknown';getDb().prepare("INSERT INTO d12_backup_receipts (id,owner_id,target_label,environment_label,checksum_sha256,backup_observed_at,evidence_refs_json,note,proof_state,restore_status,created_at) VALUES (?,?,?,?,?,?,?,?,?,'not_tested',?)").run(id,actor.id,request.target_label,request.environment_label,request.checksum_sha256,request.backup_observed_at,JSON.stringify(request.evidence_refs),request.note??null,proofState,now);audit({event_type:'d12_backup_receipt_recorded',user_id:actor.id,scope:request.environment_label,detail:{receipt_id:id,proof_state:proofState,restore_status:'not_tested',no_backup_execution:true,no_restore:true,no_deploy:true}});return toReceipt(getDb().prepare('SELECT * FROM d12_backup_receipts WHERE id=?').get(id)as D12BackupReceiptRow);}
export function listD12BackupReceipts():D12BackupReceipt[]{return(getDb().prepare('SELECT * FROM d12_backup_receipts ORDER BY backup_observed_at DESC,created_at DESC').all()as D12BackupReceiptRow[]).map(toReceipt);}
