import {CreateStoryWorkbenchRequestSchema,CreateStoryPatchCandidateRequestSchema,ROLE_RANK,SetStoryReaderStateRequestSchema,StoryPatchCandidateSchema,StoryReaderStateSchema,StoryWorkbenchSchema,type CreateStoryWorkbenchRequest,type CreateStoryPatchCandidateRequest,type StoryPatchCandidate,type SetStoryReaderStateRequest,type StoryReaderState,type StoryWorkbench} from '@masterflow/shared';
import {getDb} from '../db/schema.ts';import {uuid} from '../lib/uuid.ts';import type {AuthUser} from '../middleware/auth.ts';
function teacher(a:AuthUser):void{if(ROLE_RANK[a.role]<ROLE_RANK.teacher)throw new Error('permission_denied');}
function workbench(r:any):StoryWorkbench{return StoryWorkbenchSchema.parse({workbench_id:r.id,owner_id:r.owner_id,project_id:r.project_id,project_scope:r.project_scope,title:r.title,source_ref:r.source_ref,intake_mode:r.intake_mode,source_truth_state:r.source_truth_state,status:r.status,created_by:r.created_by,created_at:r.created_at,updated_at:r.updated_at});}
function state(r:any):StoryReaderState{return StoryReaderStateSchema.parse({reader_state_id:r.id,workbench_id:r.workbench_id,owner_id:r.owner_id,current_node:r.current_node,opening_sequence_lock:r.opening_sequence_lock,mode:r.mode,created_at:r.created_at,updated_at:r.updated_at});}
export function createStoryWorkbench(a:AuthUser,input:CreateStoryWorkbenchRequest):StoryWorkbench{teacher(a);const q=CreateStoryWorkbenchRequestSchema.parse(input),now=Date.now(),id=uuid(),scope=q.project_id??a.id;getDb().prepare("INSERT INTO story_workbenches VALUES (?,?,?,?,?,?,?,?,'draft',?,?,?)").run(id,a.id,q.project_id??null,scope,q.title,q.source_ref,q.intake_mode,q.source_truth_state,a.id,now,now);return workbench(getDb().prepare('SELECT * FROM story_workbenches WHERE id=?').get(id));}
export function setStoryReaderState(a:AuthUser,id:string,input:SetStoryReaderStateRequest):StoryReaderState{teacher(a);const w=getDb().prepare('SELECT * FROM story_workbenches WHERE id=? AND owner_id=?').get(id,a.id)as any;if(!w)throw new Error('story_workbench_not_found');const q=SetStoryReaderStateRequestSchema.parse(input),now=Date.now(),existing=getDb().prepare('SELECT * FROM story_reader_states WHERE workbench_id=? AND owner_id=?').get(id,a.id)as any;if(existing){getDb().prepare('UPDATE story_reader_states SET current_node=?,opening_sequence_lock=?,mode=?,updated_at=? WHERE id=?').run(q.current_node??null,q.opening_sequence_lock??null,q.mode,now,existing.id);return state(getDb().prepare('SELECT * FROM story_reader_states WHERE id=?').get(existing.id));}const sid=uuid();getDb().prepare('INSERT INTO story_reader_states VALUES (?,?,?,?,?,?,?,?)').run(sid,id,a.id,q.current_node??null,q.opening_sequence_lock??null,q.mode,now,now);return state(getDb().prepare('SELECT * FROM story_reader_states WHERE id=?').get(sid));}
export function createStoryPatchCandidate(a:AuthUser,id:string,input:CreateStoryPatchCandidateRequest):StoryPatchCandidate{teacher(a);if(!getDb().prepare('SELECT id FROM story_workbenches WHERE id=? AND owner_id=?').get(id,a.id))throw new Error('story_workbench_not_found');const q=CreateStoryPatchCandidateRequestSchema.parse(input),now=Date.now(),pid=uuid();getDb().prepare("INSERT INTO story_patch_candidates VALUES (?,?,?,?,?,'CANDIDATE','candidate',?,?)").run(pid,id,a.id,q.title,q.proposal,now,now);return StoryPatchCandidateSchema.parse({patch_id:pid,workbench_id:id,owner_id:a.id,title:q.title,proposal:q.proposal,truth_state:'CANDIDATE',status:'candidate',created_at:now,updated_at:now});}
export function validateStoryPatchCandidate(a:AuthUser,id:string,patchId:string):StoryPatchCandidate{teacher(a);const row=getDb().prepare('SELECT * FROM story_patch_candidates WHERE id=? AND workbench_id=? AND owner_id=?').get(patchId,id,a.id)as any;if(!row)throw new Error('story_patch_not_found');if(row.status!=='candidate')throw new Error('story_patch_not_candidate');const now=Date.now();getDb().prepare("UPDATE story_patch_candidates SET status='validated_for_canon_delta',updated_at=? WHERE id=?").run(now,patchId);const updated=getDb().prepare('SELECT * FROM story_patch_candidates WHERE id=?').get(patchId)as any;return StoryPatchCandidateSchema.parse({patch_id:updated.id,workbench_id:updated.workbench_id,owner_id:updated.owner_id,title:updated.title,proposal:updated.proposal,truth_state:updated.truth_state,status:updated.status,created_at:updated.created_at,updated_at:updated.updated_at});}
export function listStoryWorkbenches(a:AuthUser):StoryWorkbench[]{teacher(a);return(getDb().prepare('SELECT * FROM story_workbenches WHERE owner_id=? ORDER BY updated_at DESC').all(a.id)as any[]).map(workbench);}
export function listStoryPatchCandidates(a:AuthUser,id:string):StoryPatchCandidate[]{teacher(a);if(!getDb().prepare('SELECT id FROM story_workbenches WHERE id=? AND owner_id=?').get(id,a.id))throw new Error('story_workbench_not_found');return(getDb().prepare('SELECT * FROM story_patch_candidates WHERE workbench_id=? ORDER BY updated_at DESC').all(id)as any[]).map(r=>StoryPatchCandidateSchema.parse({patch_id:r.id,workbench_id:r.workbench_id,owner_id:r.owner_id,title:r.title,proposal:r.proposal,truth_state:r.truth_state,status:r.status,created_at:r.created_at,updated_at:r.updated_at}));}
