import {CreateSubjectTemplateRequestSchema, CreateSubjectVersionRequestSchema, ROLE_RANK, SubjectTemplateSchema, SubjectVersionSchema, type CreateSubjectTemplateRequest, type CreateSubjectVersionRequest, type SubjectTemplate, type SubjectVersion} from '@masterflow/shared';
import {getDb} from '../db/schema.ts';
import {audit} from '../lib/audit.ts';
import {uuid} from '../lib/uuid.ts';
import type {AuthUser} from '../middleware/auth.ts';
import {decideScopedPermission} from './projects.ts';

interface TemplateRow {id:string;owner_id:string;project_id:string|null;project_scope:string;title:string;current_version_ref:string|null;status:'draft'|'active'|'archived';created_at:number;updated_at:number;}
interface VersionRow {id:string;template_id:string;version:number;project_id:string|null;project_scope:string;manifest_json:string;status:'draft'|'validated'|'archived';created_by:string;created_at:number;}
function teacher(a:AuthUser):void{if(ROLE_RANK[a.role]<ROLE_RANK.teacher)throw new Error('permission_denied');}
function project(a:AuthUser,id:string):void{if(!decideScopedPermission({actor:a,projectId:id,minimumProjectRole:'editor'}).allowed)throw new Error('project_not_found');}
function access(a:AuthUser,t:TemplateRow):void{if(t.project_id)project(a,t.project_id);else if(t.owner_id!==a.id)throw new Error('subject_not_found');}
function templateDTO(r:TemplateRow):SubjectTemplate{return SubjectTemplateSchema.parse({template_id:r.id,owner_id:r.owner_id,project_id:r.project_id,project_scope:r.project_scope,title:r.title,current_version_ref:r.current_version_ref,status:r.status,created_at:r.created_at,updated_at:r.updated_at});}
function versionDTO(r:VersionRow):SubjectVersion{return SubjectVersionSchema.parse({version_id:r.id,template_id:r.template_id,version:r.version,project_id:r.project_id,project_scope:r.project_scope,manifest:JSON.parse(r.manifest_json),status:r.status,created_by:r.created_by,created_at:r.created_at});}
function requireTemplate(a:AuthUser,id:string):TemplateRow{const r=getDb().prepare('SELECT * FROM subject_templates WHERE id=?').get(id) as TemplateRow|undefined;if(!r)throw new Error('subject_not_found');access(a,r);return r;}
export function listSubjects(a:AuthUser,projectId?:string|null):SubjectTemplate[]{teacher(a);if(projectId){project(a,projectId);return(getDb().prepare('SELECT * FROM subject_templates WHERE project_id=? ORDER BY updated_at DESC').all(projectId)as TemplateRow[]).map(templateDTO);}return(getDb().prepare('SELECT * FROM subject_templates WHERE owner_id=? AND project_id IS NULL ORDER BY updated_at DESC').all(a.id)as TemplateRow[]).map(templateDTO);}
export function listSubjectVersions(a:AuthUser,id:string):SubjectVersion[]{teacher(a);requireTemplate(a,id);return(getDb().prepare('SELECT * FROM subject_versions WHERE template_id=? ORDER BY version DESC').all(id)as VersionRow[]).map(versionDTO);}
export function createSubject(a:AuthUser,input:CreateSubjectTemplateRequest):{template:SubjectTemplate;version:SubjectVersion}{teacher(a);const q=CreateSubjectTemplateRequestSchema.parse(input);if(q.project_id)project(a,q.project_id);const scope=q.project_id??a.id,now=Date.now(),tid=uuid(),vid=uuid(),db=getDb();db.transaction(()=>{db.prepare("INSERT INTO subject_templates VALUES (?,?,?,?,?,NULL,'draft',?,?)").run(tid,a.id,q.project_id??null,scope,q.title,now,now);db.prepare("INSERT INTO subject_versions VALUES (?,?,1,?,?,?,'draft',?,?)").run(vid,tid,q.project_id??null,scope,JSON.stringify(q.manifest),a.id,now);})();audit({event_type:'subject.created',user_id:a.id,scope,detail:{template_id:tid,version_id:vid,publication:false}});return{template:templateDTO(requireTemplate(a,tid)),version:versionDTO(db.prepare('SELECT * FROM subject_versions WHERE id=?').get(vid)as VersionRow)};}
export function createSubjectVersion(a:AuthUser,id:string,input:CreateSubjectVersionRequest):SubjectVersion{teacher(a);const t=requireTemplate(a,id),q=CreateSubjectVersionRequestSchema.parse(input),db=getDb(),now=Date.now(),vid=uuid(),max=db.prepare('SELECT COALESCE(MAX(version),0) version FROM subject_versions WHERE template_id=?').get(id)as{version:number};db.prepare("INSERT INTO subject_versions VALUES (?,?,?,?,?,?,'draft',?,?)").run(vid,id,max.version+1,t.project_id,t.project_scope,JSON.stringify(q.manifest),a.id,now);return versionDTO(db.prepare('SELECT * FROM subject_versions WHERE id=?').get(vid)as VersionRow);}
export function validateSubjectVersion(a:AuthUser,vid:string):SubjectVersion{teacher(a);const db=getDb(),v=db.prepare('SELECT * FROM subject_versions WHERE id=?').get(vid)as VersionRow|undefined;if(!v)throw new Error('subject_version_not_found');requireTemplate(a,v.template_id);if(v.status==='archived')throw new Error('subject_version_archived');const now=Date.now();db.transaction(()=>{db.prepare("UPDATE subject_versions SET status='validated' WHERE id=?").run(vid);db.prepare("UPDATE subject_templates SET current_version_ref=?,status='active',updated_at=? WHERE id=?").run(vid,now,v.template_id);})();audit({event_type:'subject.version_validated',user_id:a.id,scope:v.project_scope,detail:{version_id:vid,publication:false}});return versionDTO(db.prepare('SELECT * FROM subject_versions WHERE id=?').get(vid)as VersionRow);}
